export const modelDocumentation=`
<p class="eyebrow">VOM 3D-OBJEKT ZUM VOLUMENHOLOGRAMM</p><h2>Die Rechnung hinter dem Tor</h2>
<p>Dies ist ein skalares kohärentes Streumodell eines mikrometergroßen Lehrmodells. Es ist keine vollständige elektromagnetische Simulation der Lichtstreuung am realen Brandenburger Tor. Sämtliche Feldbilder entstehen aus komplexen Wellen; das ursprüngliche Mesh wird ausschließlich für die Objektansicht und den ausdrücklich aktivierten Geometrievergleich benutzt.</p>
<h3>1 · Oberfläche → kohärente Streuelemente</h3>
<p>Das Tor besteht aus lokal erzeugten Dreiecken. Ein orthografischer z-Puffer wählt die vom Medium aus sichtbaren Oberflächen. Die Quadratur gewichtet jedes sichtbare Element mit seiner projizierten Fläche ΔA. Das ist eine Sichtbarkeitsnäherung für eine Blickrichtung, keine vollständige Winkelabhängigkeit der Verdeckung. Elementamplituden sind fest phasenbezogen; es wird bei Qualitätswechseln keine neue Zufallsphase erzeugt.</p>
<pre>Aⱼ = g ΔAⱼ exp(i k zⱼ),  g = 3 µm⁻¹\nO(r) = Σⱼ Aⱼ exp(i k |r−rⱼ|) / |r−rⱼ|\nk = 2πn/λ₀; Zeitkonvention exp(−iωt)</pre>
<p>Der Faktor exp(ikzⱼ) beschreibt einen vorgegebenen kohärenten ebenen Antrieb in +z-Richtung. Die Oberflächen werden als unabhängige skalare Strahler behandelt. Mehrfachstreuung, BRDF, Rauheit, Polarisation, Texturen und die tatsächliche Beleuchtungs-/Abschattungsgeometrie des Monuments werden nicht modelliert. Geometrische Längen sind µm, Vakuumwellenlängen nm, die Winkel gelten intern im homogenen Medium.</p>
<h3>2 · Numerische Objektwelle</h3>
<p>Die Weyl-Entwicklung des auslaufenden Kugelwellen-Greenfelds wird im gepolsterten periodischen Fenster L = 128 µm ausgewertet. Die direkt summierten Fourierkoeffizienten lauten:</p>
<pre>Oq = (2πi / L² kₒz) Σⱼ g ΔAⱼ exp[−i(q·rⱼ,⊥ + (kₒz−k)zⱼ)]\nkₒz = √(k²−|q|²)\nO(x,y,z) = Σq Oq exp[i(q·r⊥ + kₒz z)]</pre>
<p>Nur vorwärts propagierende Komponenten mit |q| &lt; 0,28 k werden verwendet. Die äußeren 10 % dieses Winkelbands erhalten einen Kosinusauslauf. Zusätzlich gilt |q| &lt; 0,84 π min(N, 256)/L. Dies ist eine ausdrücklich bandbegrenzte, periodische Darstellung der Kugelwellensumme; evaneszente Felder fehlen. Die Polsterung und das begrenzte 48-µm-Beobachtungsfeld reduzieren zyklische Randartefakte, eliminieren sie aber nicht für beliebige Geometrien. Ein Einzelpunktvergleich gegen exp(ikR)/R ist Teil der Tests.</p>
<table><tr><th>Qualität</th><th>Oberflächenraster</th><th>Komplexes Feld</th></tr><tr><td>LIVE</td><td>64 × 64, Standardtor: 1.422 sichtbare Elemente</td><td>256 × 256; Δx = 0,5 µm</td></tr><tr><td>HIGH QUALITY</td><td>112 × 112; Zahl hängt von der Geometrie ab</td><td>512 × 512; Δx = 0,25 µm</td></tr><tr><td>FINAL</td><td>176 × 176; feinere Oberflächenquadratur</td><td>512 × 512; Δx = 0,25 µm</td></tr></table>
<p>Alle Stufen benutzen dasselbe physikalische Winkelband. Die tatsächlich verwendete Elementzahl steht in der Oberfläche. Höheres Sampling ersetzt keine größere optische Apertur. Die separaten 3D-Vorschau- und Scannerfelder interpolieren 128 × 128 × N_z komplexe Enveloppensamples in 64 × 64 × d µm; die Effizienz- und Fokusrechnung verwendet direkt die Spektralkoeffizienten und hängt nicht von diesem Vorschauraster ab. N_z = max(17, ceil(2d[k−sqrt(k²−q_max²)]/π)+1) verfeinert die Tiefenabtastung bei größerem d. Tiefere Zoomstufen erhöhen die Bildschirmauflösung, nicht die physikalische Bandbreite.</p>
<h3>3 · Was genau wird belichtet und gespeichert?</h3>
<pre>R(r) = Aᵣ exp[i(kᵣ·r + φᵣ)]\nI(r) = |O + R|² = |O|² + |R|² + 2 Re(OR*)\nδn(r) = β [I − |O|² − |R|²] = H₊(r) + H₊*(r)\nH₊(r) = β OR*</pre>
<p>Die Demo verwendet eine <strong>ideale Hintergrund- und Objekt-Selbsttermkompensation</strong>. Gespeichert wird ausschließlich der Interferenz-Kreuzterm. Das ist eine zusätzliche Idealisierung der Aufzeichnung, nicht die Behauptung, dass ein reales Material automatisch nur diesen Term speichert. Der Scanner kann vor dem Belichten die vollständige Intensität I oder den daraus gewonnenen Index-Kreuzterm zeigen. Es werden weder Sättigung, Diffusion, Schrumpfung noch eine Photochemie berechnet.</p>
<p>Der Snapshot enthält die komplexen Koeffizienten des Index-Seitenbands und dessen analytischen Referenzträger. Die reelle Indexstruktur ist dadurch im ganzen Volumen definiert. Referenzphase und -amplitude sind in den Koeffizienten enthalten. Nach dem Belichten wird die Objektwelle ausgeschaltet. Die Rekonstruktionsfunktion erhält keine Geometrie, keinen Streupunktdatensatz und kein Bild des Tors. Der Export enthält nur diese Indexrepräsentation.</p>
<h3>4 · Rekonstruktion: spektrale erste Born-Näherung</h3>
<p>Jede aufgenommene Objektkomponente trägt ihren eigenen Gittervektor Kq = (q,kₒz) − kᵣ. Es gibt kein einziges globales K. Für eine ebene Lesewelle kᵢ wird die +1-Ordnung kohärent berechnet:</p>
<pre>q_d = q + kᵢ,⊥ − kᵣ,⊥\nk_dz = √(k_read² − |q_d|²)\nΔq = kᵢz + kₒz − kᵣz − k_dz\nDq(d) = i (k₀,read² n / k_dz) Hq Aᵢ d\n        × sinc(Δq d/2) exp[i(k_dz d + Δq d/2)]</pre>
<p>Das sinc ist das analytische Volumenintegral von z = 0 bis d, keine aufgesetzte Unschärfe. Vorzeichen, Phase und detuningspezifische Querwellenvektoren werden bei der Rekombination erhalten. Bei passender Geometrie verschwindet Δq für jede zulässige Komponente. Eine größere Dicke erhöht die Phasenselektivität. Die Vergleichskurve hält βd konstant, damit die triviale d²-Skalierung der schwachen Beugung den Breitenvergleich nicht verdeckt.</p>
<p><strong>Gültigkeit:</strong> schwache Indexstörung und undepletierte Lesewelle; keine Rückkopplung und keine Mehrfachstreuung zwischen den vielen Objektordnungen. Das ist keine Anwendung einer einzelnen Kogelnik-Formel auf das ganze Tor. Nur die selektierte positive Hologrammordnung wird berechnet, keine Null- oder konjugierte Ordnung. Die quantitative Effizienz wird nur bei η &lt; 5 % und verworfenem Spektralgewicht &lt; 0,5 % angezeigt. Auch unterhalb dieser Schwellen ist dies keine garantierte Fehlerabschätzung. Transmittierte Leistung wird ausdrücklich nicht vorhergesagt.</p>
<h3>5 · Apertur, Beobachter und virtuelle Fokusebene</h3>
<pre>E_exit(x,y) = IFFT{Dq} × P(x,y)\nE_focus(x,y,z_f) = IFFT{FFT[E_exit] exp[−i k_z (d + z_f)]}\nBild = |E_focus|²</pre>
<p>P ist eine reale Amplitudenmaske auf der Austrittsfläche. Die Varianten „links“, „rechts“, „Fenster“ und die seitlich bewegte Beobachterpupille wirken auf die komplexe Welle, bevor sie propagiert wird. Die Pupillenränder haben einen 1-µm-Kosinusauslauf. „Zerbrechen“ bedeutet hier optisches Abdecken am Ausgang; ein mechanisch herausgebrochenes, lateral endliches Streuvolumen und dessen innere Randbeugung werden nicht simuliert.</p>
<p>Die negative Propagationsdistanz zeigt ein <strong>numerisch refokussiertes virtuelles Bild</strong>. Ein physischer Schirm hinter dem Hologramm würde dieses virtuelle Tor nicht ohne abbildende Optik direkt zeigen. Die Beobachterverschiebung wählt eine verschobene Austrittspupille mit paralleler Achse. Auf einer gemeinsamen Fokusebene ist im paraxialen Schwerpunktlimit Δx = Δp [1 − (z_f+d)/(z_obj+d)]. Unterschiedliche Tiefen ergeben somit unterschiedliche relative Parallaxe; exakt fokussierte Punkte behalten bei dieser Koordinatenkonvention ihre Objektposition.</p>
<p>η ist der nach der Austrittspupille per Angular Spectrum summierte Vorwärtsfluss, bezogen auf eine Einheitslesewelle über der quadratischen nominellen Hologrammapertur. Dabei wird jede Komponente mit k_z/kᵢz gewichtet. Die Feldtreue ist der normierte Betrag des komplexen Überlapps mit der passenden Rekonstruktion bei gleicher Pupille und Fokuslage, kein Vergleich mit einem gerenderten Mesh. Bildhelligkeit und Bildbelichtung bleiben bei Detuning vergleichbar; sie werden nicht automatisch wieder hochgeregelt.</p>
<h3>6 · Lokale Gittervektoren und k-Raum</h3>
<p>Die lokale Analyse verwendet eine gaußgewichtete Fenster-FFT des tatsächlich berechneten Felds, σ = 2 µm. Bis zu drei getrennte echte lokale Maxima oberhalb von 3 % des stärksten Maximums repräsentieren Beiträge, keine eindeutigen einzelnen Streuer. Bei einer einzelnen ebenen Welle erscheint nur ein Maximum. Ein kurzer lokaler Ausschnitt kann Objektpunkte nicht eindeutig identifizieren. Die lokalen K-Vektoren sind jeweils die Differenz zum Referenzvektor; die Fringenebenen stehen normal zu K. Der k-Raum-Scanner ist eine FFT des aktuellen numerischen Schnitts nach Mittelwertabzug und Hann-Fensterung. Er ist eine zweidimensionale Schnittanalyse, kein vollständiges dreidimensionales Leistungsspektrum des Mediums.</p>
<h3>7 · Was der Vergleich „Zerlege das Tor“ zeigt</h3>
<p>Für vergleichbare Sichtbarkeit wird zunächst das ganze Tor diskretisiert und dann in feste Gruppen zerlegt. Die vollständige gemeinsame Intensität unterscheidet sich von der Summe der Einzelintensitäten (Referenz einmal gezählt) um 2 Re(Oₛ Oq*). Nach der hier verwendeten idealen Selbsttermkompensation ist der Index-Kreuzterm linear in O. Deshalb ist es korrekt, dass sich die kompensierten Index-Seitenbänder kohärent addieren, obwohl sich die vollständigen Belichtungsintensitäten unterscheiden.</p>
<h3>8 · Geprüft und bewusst ausgelassen</h3>
<p>Ausführbare Tests prüfen Einzelpunkt, zwei Punkte, Planwellenregression zum schwachen bisherigen Gitterfall, getrennte Tiefenfoki, Parallaxe, Teilabdeckung, Winkel-/Wellenlängendetuning, Dickenselektivität, Mesh-Unabhängigkeit und Konvergenz. Beim Standardtor ergeben sich gegenüber FINAL für 1−Feldtreue etwa 0,03456 (LIVE) und 0,00998 (HIGH). FINAL ist eine feinere numerische Referenz, keine analytisch bewiesene exakte Lösung.</p>
<p>Nicht enthalten: vektorielle Maxwell-/RCWA-Rechnung, Polarisation, Reflexionsholografie, Dispersion, Absorption, Fresnel-Grenzflächen, Mehrfachstreuung, Materialchemie, reale Fertigungsparameter, produktspezifische Verfahren, Textur-/Materialeigenschaften importierter Meshes oder exakte Rundumsichtbarkeit. Das Modell ist eine wissenschaftlich begrenzte, kohärente Lehrsimulation.</p>
<p>Methodischer Bezug: <a href="https://doi.org/10.1364/AO.50.001038" target="_blank" rel="noreferrer">Spatial-spectral volume holographic systems: resolution dependence on effective thickness</a> (Born-Beschreibung von Volumenhologrammen); die implementierten Gleichungen und zusätzlichen Idealisierungen sind oben ausdrücklich angegeben.</p>`;
