export const documentation = `
<p>Die Demo hat zwei getrennte Rekonstruktionsmodelle. Alle Längen sind intern in µm, Zeiten in fs und Winkel in rad. Regler zeigen <strong>interne</strong> Winkel zur +z-Normalen und <strong>Vakuumwellenlängen</strong>. n ist reell und dispersionsfrei. Das Volumen ist eine Scheibe 0 ≤ z ≤ d in einem indexangepassten Umgebungsmedium.</p>
<h3>1 · Aufzeichnung: komplexe skalare Felder</h3>
<div class="math">Eᵣ(r,t) = Aᵣ exp[i(kᵣ·r + φᵣ − ωᵣt)]<br>Eₒ(r,t) = Aₒ exp[i(kₒ·r + φₒ − ωₒt)]<br>kⱼ = (2πn/λ₀ⱼ)(sin θⱼ, 0, cos θⱼ)<br>I = Aᵣ² + Aₒ² + 2 AᵣAₒ cos(Φₒ − Φᵣ)</div>
<p>Die Intensität ist in |E₀|² angegeben; der gemeinsame elektromagnetische Vorfaktor ist weggelassen. Im ebenen Modus gilt feste gemeinsame s-Polarisation (E entlang y), keine polarisationsabhängige Regelung. Im Kugelwellenmodell sind die Felder rein skalar.</p>
<div class="math">K = kₒ − kᵣ ; Λ = 2π/|K|<br>Bei gleicher λ₀: Λ = λ₀ / [2n sin(α/2)]<br>Kugelwelle: Eₒ = Aₒ(R₀/R) exp[i(kₒR + φₒ − ωₒt)]<br>R = |r − r₀| ; R₀ = |r₀|</div>
<p>r₀ liegt außerhalb des Mediums bei z &lt; 0 und beschreibt einen mathematischen divergenten Objektpunkt. Aₒ ist auf den Ursprung der Eintrittsebene normiert. Die Richtung ist bei der Kugelwelle ortsabhängig und wird durch r₀ eingestellt. Für K = 0 gibt es keine räumliche Differenzperiodizität; eine konstante Phasendifferenz ändert nur die konstante Intensität.</p>
<h3>2 · Speichern: lineare Belichtung, keine Chemie</h3>
<div class="math">sinc(x) = sin(x)/x ; Δω = ωₒ − ωᵣ<br>⟨I⟩ = I_dc + 2 AᵣAₒ(r) sinc(Δω T/2) cos(Φₒ − Φᵣ)<br>δn(r) = Δn_Regler · D · [⟨I(r)⟩ − I_dc(r)] / 2</div>
<p>Das Belichtungsfenster [−T/2,T/2] ist um t = 0 zentriert. D ist ein dimensionsloser Dosisfaktor. Bei zwei Einheitsamplituden, gleicher Frequenz und D = 1 ist Δn_Regler die Spitzenamplitude des Cosinusgitters. Die örtliche DC-Komponente wird bewusst entfernt, auch die Kugelwellenhülle. Ein konstanter Rest bei K = 0 gilt als Hintergrundindexänderung und erzeugt keine separate Ordnung. Unterschiedliche λ₀ ergeben im Allgemeinen wandernde Interferenz; bei langer Belichtung mittelt der Kreuzterm aus. Die Liveansicht zeigt dann ausdrücklich nur die Momentaufnahme t = 0.</p>
<p>Gespeichert wird eine unabhängige Kopie der analytischen Feldparameter. Die Funktion δn(r) bleibt damit ohne Voxelisierungsfehler erhalten. Eine lokale Browserkopie übersteht das Neuladen; JSON-Export ist möglich. Nachträgliches Ändern von d bedeutet Ausschneiden/Extrudieren desselben analytischen Gitters; Δn skaliert seine Amplitude. Beides ist ein Parameterexperiment, kein Herstell- oder Schrumpfmodell.</p>
<h3>3 · Ebenes Gitter: fluxnormiertes Zweiwellenmodell</h3>
<p>Verlustfreies, sinusförmiges, vorwärts streuendes Transmissionsgitter; konstante Kopplung, zwei Ordnungen, langsam veränderliche Amplituden (SVEA), bragg-nah. Aus der skalaren Helmholtzgleichung werden Terme O(δn²) im Brechungsindexquadrat sowie zweite z-Ableitungen der Hüllen vernachlässigt. Die Richtung der elastischen Ausgangsordnung wird bei Detuning nicht durch einen off-shell Vektor ersetzt:</p>
<div class="math">k = 2πn/λ₀ ; k_d,∥ = k_i,∥ + K∥<br>k_d,z = +√(k² − |k_d,∥|²)<br>Δ = k_i,z + K_z − k_d,z<br>c_i = k_i,z/k ; c_d = k_d,z/k<br>κ = π Δn_eff / [λ₀ √(c_i c_d)]<br>ν = κd ; ξ = Δd/2<br>η = ν² sinc²(√(ν² + ξ²)) ; T₀ = 1 − η</div>
<p>Δn_eff = |Δn_Regler D Aᵣ Aₒ sinc(ΔωT/2)|. η und T₀ sind Anteile des Flusses durch z-Ebenen, nicht einfach elektrische Amplitudenquadrate. Nach Phasentransformation erfüllen die fluxnormierten Hüllen ein hermitesches 2×2-System mit Diagonale ±Δ/2 und Kopplung κ. Damit bleibt η + T₀ = 1. Dies ist eine explizit definierte, Kogelnik-artige SVEA mit elastischer Ausgangsrichtung; keine Behauptung einer vollständigen RCWA- oder Grenzflächenlösung.</p>
<p>Bei Δ = 0 gilt η = sin²ν. ν = π/2 ergibt volle Konversion; höhere Modulation kann Energie zurückkoppeln. Deshalb ist die Aufnahmegeometrie nicht bei beliebiger Stärke ein globales Maximum, und Detuning wirkt nicht global monoton: Nebenmaxima bleiben sichtbar. Die Vergleichskurve verwendet d/4 und 4Δn, also identisches ν.</p>
<div class="math">Q = 2π λ₀ d / (nΛ²)<br>ρ = λ₀² / (n Δn_eff Λ²)</div>
<p>Die Demo gibt quantitative Zweiwellenwerte nur bei Q ≥ 10, ρ ≥ 10, |Δ|/k ≤ 0,1 und c_i,c_d ≥ 0,25 aus. Dies sind konservative Anzeigeschranken, keine hinreichenden Fehlergarantien. Nicht propagierende Ordnungen und ungültige Scanabschnitte werden ausgelassen. Die dünne Grenze benötigt Mehrordnungstheorie (Raman–Nath/RCWA); eine dünne Phasenmaske wird hier nicht als zweiter Kogelnik-Modus ausgegeben.</p>
<h3>4 · Kugelwelle: numerische Vorwärts-Born-Rekonstruktion</h3>
<p>Hier wird ausschließlich der objekttragende komplexe Kreuzterm δn₊ = Δn_Regler D sinc(ΔωT/2) AᵣAₒ(r) exp[i(Φₒ−Φᵣ)]/2 rekonstruiert. Die reelle gespeicherte Modulation enthält zusätzlich das konjugierte Gegenstück; dessen Gegenordnung wird in diesem ausgewählten Rekonstruktionskanal nicht mitgerechnet.</p>
<div class="math">Ẽ_d(q∥,d) = i k₀² n / q_z ∫₀ᵈ dz<br>　 exp[iq_z(d−z)] ℱ_xy{δn₊(r) E_i(r)}<br>q_z = +√[(nk₀)² − |q∥|²]</div>
<p>Dies ist das auslaufende skalare Helmholtz-Green-Modell erster Born-Ordnung mit ungeschwächter ebener Beleuchtung. Das Austrittsfeld wird durch komplexe Summation vieler Tiefenscheiben und inverse 2D-FFT berechnet. Phase ist zyklisch farbcodiert; Helligkeit zeigt den relativen Feldbetrag. Die Richtungs- und Wellenlängenänderungen wirken im Volumenintegral, nicht durch eine nachträglich aufgesetzte Bragg-Kurve.</p>
<p>Standardraster: 256², bei starker Quellphasensteigung adaptiv 512², periodisch gepolstertes Fenster 24 × 24 µm, Wechselwirkungsbereich 6 × 4,5 µm mit einem Kosinus-Randfenster (je 0,75 µm) zur Reduktion der spektralen Rasterfehler, mindestens 64 Tiefenscheiben, Δz ≤ 0,3 µm und geschätzter maximaler longitudinaler Phasenschritt ≤ π/2 (Ausgangsfall: 337 Scheiben). Der Querrasterbedarf wird vor der FFT aus den lokalen Phasensteigungen geprüft; über 512² wird die Rechnung angehalten. Berücksichtigt wird q_z/k ≥ 0,25. Der unterdrückte Quellspektrumsanteil wird ausgewiesen. Die endliche periodische Box und die endliche Wechselwirkungsapertur begrenzen die Genauigkeit. Das Randfenster multipliziert nur den Streuquellterm und ist Teil der numerischen Aperturdefinition, keine Materialeigenschaft. Die angezeigte Leistung ist über das gesamte berechnete FFT-Fenster und mit q_z/k_i,z gewichtet; der Referenzfluss ist der einer Einheitswelle durch die vollen 6 × 4,5 µm.</p>
<p><strong>η ≤ 10 % und weniger als 1 % abgeschnittenes Quellspektrum</strong> sind Anzeigeschranken, keine universelle Born-Fehlerabschätzung. Darüber ist die Lösung nur ein diagnostisches Born-Feld. Es gibt hier keine berechnete transmittierte Restleistung: Born enthält keine Depletion. Der graue Strahl ist die ungeschwächte Modellbeleuchtung. Der ebene Effizienzscan wird im Kugelmodus durch das numerische Austrittsfeld ersetzt.</p>
<h3>5 · Was genau wird gezeichnet?</h3>
<p>Beim ebenen Gitter ergänzen exakte geometrische Flächen gleicher Phase die Volumenansicht (bis 100 Flächen, keine Fringendezimation). Der WebGL-Raymarcher wertet die analytische Feldstruktur an 256 Positionen pro Sehstrahl im gesamten Volumen aus. Transparenz und Leuchtfarbe sind eine illustrative Transferfunktion, keine Simulation von Streulicht am Beobachter. Der farbige Schnitt berechnet dasselbe Feld separat (480 × 240). Im Speichermodus ist seine Farbskala automatisch normiert; die Werte an der Skala sind δn. Die Momentaufnahme verwendet 0…4 |E₀|², höhere Intensitäten sättigen farblich.</p>
<p>Die Box zeigt einen 6 × 4,5 × d µm großen Ausschnitt, die z-Achse ist zur Lesbarkeit komprimiert. Bei schrägen und sehr feinen Gittern kann die endliche Abtastung Muster nicht auflösen; der xy-Schnitt ist dann vorzuziehen. Äußere Strahlen und ausgewählte Wellenfronten sind schematisch, nicht Teil dieser Achsenskalierung. Ihre Animation steht nicht für reale optische Zeit. Das k-Diagramm zeigt die tatsächlichen internen Vektoren; bei Kugelwellen nur die lokale Tangente am Ursprung.</p>
<h3>6 · Bewusst nicht abgebildet</h3>
<p>Materialchemie, reale Empfindlichkeit, Sättigung, Diffusion, Entwicklung, Schrumpfung, Absorption, Fresnel-Verluste, äußere Ein-/Auskopplung, Indexdispersion, Streuung, Speckle, endliche Kohärenzlänge, Rauschen, Mehrfachreflexionen, Reflexionshologramme, volle vektorielle Polarisation, thermische/mechanische Effekte, Fertigungstoleranzen und produktspezifische Verfahren. Der ebene Modus nimmt lateral unendliche Ausdehnung an. Die beiden Rekonstruktionsmodelle sind keine universelle Maxwell-Simulation.</p>
<h3>7 · Nachvollziehbare Referenzen und Prüfung</h3>
<p><a href="https://doi.org/10.1002/j.1538-7305.1969.tb01198.x" target="_blank" rel="noreferrer">H. Kogelnik (1969), Coupled Wave Theory for Thick Hologram Gratings</a> ist die Referenz für die Zweiwellen-Näherung. Die Bedeutung elastischer Ausgangsvektoren bei Detuning wird u. a. von <a href="https://arxiv.org/abs/1203.5714" target="_blank" rel="noreferrer">Fally, Klepp & Tomita (2012/2014)</a> untersucht. Diese Demo definiert ihre eigene Flussnormierung ausdrücklich oben.</p>
<p>Die mitgelieferten Tests vergleichen Fringenperiode, Bragg-Peak, Detuning, Dicken-Skalierung, Belichtungsmittelung, unveränderten Zustand beim Ansichtswechsel und Snapshot-Isolation. Die Zweiwellenformel wird gegen eine unabhängige RK4-Integration geprüft. Für die Born-Rekonstruktion gibt es FFT-/Parseval-, Nullfeld-, quadratische Skalierungs-, analytische Kontroll- und Tiefenkonvergenztests. Ausführbare Fälle und erwartete Resultate: <code>tests/model.test.mjs</code> und <code>docs/TESTS.md</code>.</p>
`;
